version: '2'

services:
#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    container_name: post_it_web_app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=post_it_user
#      - SPRING_DATASOURCE_PASSWORD=post_it_user_password
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: post_it_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postit
      - POSTGRES_USER=post_it_user
      - POSTGRES_PASSWORD=post_it_user_password