version: '3.5'

services:
  postit_app:
    image: 'postit-app:latest'
    build:
      context: .
    container_name: post_it_web_app
    ports:
      - ${POSTIT_BACKEND_PORT}:8080
    depends_on:
      - postit_db
    environment:
      - POSTIT_DB_NAME=${POSTIT_DB_NAME}
      - POSTIT_DB_USER=${POSTIT_DB_USER}
      - POSTIT_DB_PASSWORD=${POSTIT_DB_PASSWORD}
      - POSTIT_DB_PORT=${POSTIT_DB_PORT}
      - POSTIT_DB_HOST_NAME=${POSTIT_DB_HOST_NAME}
  postit_db:
    image: 'postgres:13.1-alpine'
    container_name: ${POSTIT_DB_HOST_NAME}
    ports:
      - ${POSTIT_DB_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTIT_DB_NAME}
      - POSTGRES_USER=${POSTIT_DB_USER}
      - POSTGRES_PASSWORD=${POSTIT_DB_PASSWORD}
  postit_db_test:
    image: 'postgres:13.1-alpine'
    container_name: postit_db_test
    ports:
      - ${POSTIT_DB_PORT_TEST}:5432
    environment:
      - POSTGRES_DB=${POSTIT_DB_NAME_TEST}
      - POSTGRES_USER=${POSTIT_DB_USER_TEST}
      - POSTGRES_PASSWORD=${POSTIT_DB_PASSWORD_TEST}