version: 2.1

jobs:
  verify-frontend:
    working_directory: ~/postit/frontend
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
        path: ~/postit
      - run:
          name: Checking current dir
          command: ls -la
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install local dependencies
          command: npm install
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

workflows:
  verification:
    jobs:
      - verify-frontend:
          filters:
            branches:
              only:
                - master
